# Generated by Django 5.0.1 on 2024-01-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='purchased_books',
            field=models.IntegerField(null=True),
        ),
    ]
