# Generated by Django 5.0.1 on 2024-02-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='titlle_book',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
