# Generated by Django 5.0.1 on 2024-03-02 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_users_id_books_remove_users_titlle_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='books',
            new_name='purchased_books',
        ),
    ]
