# Generated by Django 5.0.1 on 2024-01-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('active', models.BooleanField()),
                ('description', models.TextField()),
            ],
        ),
    ]
