# Generated by Django 5.0.1 on 2024-01-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_books_author_alter_books_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.FloatField(),
        ),
    ]
