# Generated by Django 5.0.1 on 2024-03-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviews_user_alter_reviews_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='user',
        ),
        migrations.AddField(
            model_name='reviews',
            name='user_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
