# Generated by Django 5.0.1 on 2024-03-16 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_reviews_user_reviews_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='user_name',
            new_name='user_nam',
        ),
    ]
