# Generated by Django 5.0.1 on 2024-03-16 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_rename_user_name_reviews_user_nam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='user_nam',
            new_name='user_name',
        ),
    ]
