# Generated by Django 5.0.1 on 2024-03-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_rename_user_nam_reviews_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
    ]
